//
// Created by 钟华松 on 16/11/27.
//

#ifndef KEYCONTENTEXTRACTIONFROMVIDEO_GLOBAL_VALUE_H
static const char* PRE_PROCESS_INPUT_FILE_NAME = "";
static const char* PRE_PROCESS_OUTPUT_DIR = "";
static int SAMPLE_INTERVAL = 3;
#define KEYCONTENTEXTRACTIONFROMVIDEO_GLOBAL_VALUE_H

#endif //KEYCONTENTEXTRACTIONFROMVIDEO_GLOBAL_VALUE_H
